<main>
    
    <form action="<?= route('handleLogin') ?>" method="POST">
        <h1>Connection</h1>
        <p>
            <label for="email">Email</label>
            <input type="email" id="email" name="email"/>
        </p>
        <p>
            <label for="password">Password</label>
            <input type="password" id="password" name="password"/>
        </p>
        <button type="submit">Connection</button>
    </form>
    
</main>