<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="<?= asset('css/app.css') ?>" type="text/css" />
</head>
<body>
    
    <header>
        <nav>
            <a href="<?= route('home') ?>">Home</a>
            <a href="<?= route('register') ?>">Register</a>
        </nav>
    </header>
    
    <?php include_once $view; ?>

    <?php if( [] !== $flashbag = \Core\FlashBag::get() ) : ?>
    
        <div id="flashbag" class="<?= $flashbag['type'] ?>">
            <span>
                <?= $flashbag['message'] ?>
            </span>
        </div>
    
    <?php endif; ?>
    
</body>
</html>