<main>
    
    <form action="<?= route('handleRegister') ?>" method="POST">
        <h1>Register</h1>
        <p>
            <label for="username">Username</label>
            <input type="text" id="username" name="username"/>
        </p>
        <p>
            <label for="email">Email</label>
            <input type="email" id="email" name="email"/>
        </p>
        <p>
            <label for="password">Password</label>
            <input type="password" id="password" name="password"/>
        </p>
        <button type="submit">Create account</button>
    </form>
    
</main>