    <?php foreach ($books as $book) : ?>
        <tr>
            <td><?php echo $book['id']; ?></td>
            <td><?php echo $book['title']; ?></td>
            <td><?php echo $book['author']; ?></td>
            <td><?php echo $book['cover']; ?></td>
            <td><?php echo $book['published_at']; ?></td>
            <td><?php echo $book['category_id']; ?></td>
            <td><?php echo $book['user_id']; ?></td>
        </tr>
    <?php endforeach; ?>